project_id = "viqkciphnwdsjovhpokm"

[functions.tribopay-create-pix]
verify_jwt = false

[functions.tribopay-webhook]
verify_jwt = false

[functions.async-create-pix]
verify_jwt = false

[functions.async-webhook]
verify_jwt = false
